services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiAccessibility\:
    resource: '../Classes/*'

  Maispace\MaiAccessibility\Controller\:
    resource: '../Classes/Controller/*'
    public: true
